# Generated by Django 4.1.3 on 2023-03-02 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('precio', models.IntegerField(max_length=20)),
                ('estado', models.BooleanField(default=False)),
                ('anio', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=10, verbose_name='Apellido de la persona'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre de la persona'),
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('data', models.DateField()),
                ('valoracion', models.IntegerField()),
                ('estado', models.CharField(choices=[('L', 'Leido'), ('N', 'No leido'), ('E', 'Error'), ('A', 'Aceptado')], max_length=1)),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='product',
            field=models.ManyToManyField(to='usuarios.producto', verbose_name='Los productos del usuario'),
        ),
    ]
